// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <Arduino_ConnectionHandler.h>

const char SSID[]     = Lucas;    // Network SSID (name)
const char PASS[]     = 123456789abc;    // Network password (use for WPA, or use as key for WEP)


WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);