// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSniderChange();
void onKnapChange();

float frequency;
float oUTPUTDATATOWEB;
float vrmsdash;
int snider;
bool knap;

void initProperties(){

  ArduinoCloud.addProperty(frequency, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(oUTPUTDATATOWEB, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(vrmsdash, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(snider, READWRITE, ON_CHANGE, onSniderChange, 1);
  ArduinoCloud.addProperty(knap, READWRITE, 1 * SECONDS, onKnapChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);